module.exports = {
  siteMetadata: {
    title: 'Maya Sweedler',
    clips: [
      {"articleURL": "https://www.latimes.com/politics/la-me-pol-mimi-walters-young-kim-201891112-story.html", "title": "GOP sees leads shrink in Orange County congressional races", "description": "Democrats in two undecided Orange County congressional races further narrowed the gap Monday against their GOP rivals, as ongoing ballot-counting continued to favor Democratic candidates throughout the state.", "imageURL": "https://i.imgur.com/mMDWOoe.jpg", "genre": "Political", "publication": "LA Times", "importance": "least"},
      {"articleURL": "https://www.post-gazette.com/sports/olympicfeatures/2016/08/05/Hopewell-s-Christa-Harmotto-Dietzen-displays-strength-of-character-on-and-off-volleyball-court/stories/201607250003", "title": "Hopewell's Christa Harmotto Dietzen displays strength of character, on and off volleyball court", "description": "Dietzen, 29, is headed back to the Olympics this week, this time as the captain of the No. 1 women\u2019s volleyball team in the world.", "imageURL": "https://i.imgur.com/Gy1TenK.jpg", "genre": "Sports", "publication": "Pittsburgh Post Gazette", "importance": "least"},
      {"articleURL": "https://www.post-gazette.com/ae/books/2016/08/28/From-Nadia-to-Simone-surpassing-perfection-in-gymnastics/stories/201608280015", "title": "The End of the Perfect 10': From Nadia to Simone, surpassing perfection in gymnastics", "description": "Seething beneath the book\u2019s surface is the Cold War-style binary that has defined women\u2019s gymnastics for the past 40 years. It is difficult to refute the fact that the baton has passed from Russia to the United States, but Ms. Meyers\u2019 deft explanation shows why the Americans have superseded the Russians.", "imageURL": "https://i.imgur.com/11sSH1z.jpg", "genre": "Features", "publication": "Pittsburgh Post Gazette", "importance": "least"},
      {"articleURL": "https://yaledailynews.com/blog/2016/04/11/astro-dept-ahead-on-sexual-harassment/", "title": "Astro department ahead on sexual harassment", "description": "Meg Urry is, in some ways, considered the face of a Yale science department that holds a unique place in the national dialogue. With a faculty that is 28.6 percent female \u2014 well-above the American Institute of Physics\u2019 reported national rate of 19 percent among astronomy departments \u2014 Yale astronomy has created a more open, welcoming environment for its women.", "imageURL": "https://i.imgur.com/BkWDIQW.jpg", "genre": "Features", "publication": "YDN", "importance": "least"},
      {"articleURL": "https://www.latimes.com/politics/la-me-ca-pol-hunter-letter-20181015-story.html", "title": "Hunter repeats unfounded claim that opponent is 'a national security risk'", "description": "Rep. Duncan Hunter, the indicted Republican from Alpine, has doubled down on unfounded attacks on his opponent with a letter signed by three retired Marine Corps generals who accused the Democrat of being \u201ca national security risk.\u201d", "imageURL": "https://i.imgur.com/BBaOXWm.jpg", "genre": "Political", "publication": "LA Times", "importance": "moderately"},
      {"articleURL": "https://www.wsj.com/articles/puerto-ricos-hotels-offer-rare-good-news-in-aftermath-of-the-hurricane-1534849200", "title": "Puerto Rico\u2019s hotels offer rare good news in hurricane aftermath", "description": "Buoyed by demand from relief workers and a surprisingly strong showing from tourists, the territory\u2019s hotels are enjoying better-than-expected results.", "imageURL": "https://i.imgur.com/roUdO5c.jpg", "genre": "Features", "publication": "Wall Street Journal", "importance": "moderately"},
      {"articleURL": "https://yaledailynews.com/blog/2016/03/10/mens-basketball-captain-expelled-for-sexual-misconduct/", "title": "Men\u2019s basketball captain expelled for sexual misconduct", "description": "Jack Montague, former captain of the Yale men\u2019s basketball team, was expelled from the University for sexual misconduct, the News confirmed on Wednesday. A formal complaint was filed against Montague with the University-Wide Committee on Sexual Misconduct in November of 2015, several months after an incident of alleged misconduct occurred.", "imageURL": "https://i.imgur.com/wpMCxYM.jpg", "genre": "Investigative", "publication": "YDN", "importance": "moderately"},
      {"articleURL": "http://features.yaledailynews.com/blog/2015/04/24/part-ii-the-summer/ ", "title": "2020 \u2014 Chronicling Ivy League recruitment", "description": "Not every high school football player is woken up by a call from a Division I university. As football recruiting for the class of 2020 approaches its peak, high school athletes around the country are seeking the one thing that can get them that phone call: exposure.", "imageURL": "https://i.imgur.com/HfOnOBX.jpg", "genre": "Sports", "publication": "YDN", "importance": "moderately"},
      {"articleURL": "https://www.latimes.com/politics/la-me-pol-ca-veterans-ca-50-20181101-story.html", "title": "Hunter, Campa-Najjar look to veterans to portray each other as unfit to serve", "description": "About 10% of the exurban district\u2019s population served in the Armed Forces, among the highest rates in California, U.S. census data show. In Escondido, one of the district\u2019s largest cities, 45 hero banners fly from Memorial Day to Armistice Day every year to honor some of the locals who\u2019ve served.", "imageURL": "https://i.imgur.com/Z6WGo6f.jpg", "genre": "Political", "publication": "LA Times", "importance": "most"},
      {"articleURL": "https://www.seattletimes.com/seattle-news/recent-problems-with-seafair-pirates-recall-groups-rowdiest-days/", "title": "Seafair Pirates, accused of targeting women and showing up drunk, no longer welcome at some festivals", "description": "Each flag\u2019s colorful stripes and shapes represent a letter of the alphabet, which can be decoded into a message. At many events, including the parade in Puyallup earlier this April, the message was directed at the women in the crowd: \u201cShow us your tits.\u201d", "imageURL": "https://i.imgur.com/2Za5tzB.jpg", "genre": "Investigative", "publication": "Seattle Times", "importance": "most"},
      {"articleURL": "https://www.latimes.com/politics/la-pol-na-duncan-hunter-islam-20180926-story.html", "title": "In speech, Hunter implies campaign rival is a radical Muslim", "description": "U.S. Rep. Duncan Hunter, the Alpine Republican fighting charges of misusing campaign funds, appeared to suggest in a speech to a women\u2019s group that his election opponent is a \u201cradical Muslim.\"", "imageURL": "https://i.imgur.com/asPV1mh.jpg", "genre": "Political", "publication": "LA Times", "importance": "somewhat"},
      {"articleURL": "https://www.latimes.com/politics/la-me-pol-knight-veterans-brayton20181101-story.html", "title": "Rep. Steve Knight's campaign removes ad featuring racist supporter", "description": "Rep. Steve Knight\u2019s campaign on Thursday took down an advertisement featuring a local veteran who regularly posts racist, anti-Muslim and anti-Semitic comments on social media, a day after the congressman\u2019s camp said it would not remove the political spot.", "imageURL": "https://i.imgur.com/20WHf0H.jpg", "genre": "Political", "publication": "LA Times", "importance": "somewhat"},
      {"articleURL": "https://www.wsj.com/articles/heavy-breathing-in-manhattan-park-is-not-what-anyone-thinks-it-is-1530548292", "title": "Heavy breathing in Manhattan park is not what anyone thinks it is", "description": "\u201cMy first thought was dinosaurs,\u201d said New York resident Michelle Guelbart, who strolled through last week and figured the sounds were a promotion for this summer\u2019s \u201cJurassic World\u201d movie. \u201cI was definitely surprised by the sounds, though not alarmed, because this is New York City.\u201d ", "imageURL": "https://i.imgur.com/dGHLE4v.jpg", "genre": "Features", "publication": "Wall Street Journal", "importance": "somewhat"},
      {"articleURL": "https://www.wsj.com/articles/jeff-daniels-never-wanted-to-do-hamlet-but-atticus-finch-is-role-of-a-lifetime-1536238801", "title": "Jeff Daniels never wanted to do Hamlet, but Atticus Finch is \u2018role of a lifetime'", "description": "Performing \u201cTo Kill a Mockingbird\u201d live on stage creates both a challenge and an opportunity to make Ms. Lee\u2019s story more immediate and more current, Mr. Daniels said.", "imageURL": "https://i.imgur.com/vHf0shx.jpg", "genre": "Features", "publication": "Wall Street Journal", "importance": "somewhat"},
      {"articleURL": "https://newsinteractive.post-gazette.com/penguins/50/cup-returns-to-pittsburgh/", "title": "Stanley Cup returns to Pittsburgh", "description": "After firing the coach that led them to the Stanley Cup finals the previous year, the Penguins get hot \u2014 and get even \u2014 with the team that cost them the Cup one year earlier.", "imageURL": "https://i.imgur.com/BfvtN5z.jpg", "genre": "Sports", "publication": "Pittsburgh Post Gazette", "importance": "somewhat"},
      {"articleURL": "https://yaledailynews.com/blog/2016/09/09/brained/", "title": "Brained", "description": "One set of institutions has recently begun to step up to address traumatic brain injuries, one of the most contentious and misunderstood topics in modern medicine: college athletic conferences. With the strictest safety regulations in all of Division I athletics and a multimillion-dollar promise to continue research, the Ivy League is poised to take the lead.", "imageURL": "https://i.imgur.com/DCjFo3z.jpg", "genre": "Sports", "publication": "YDN", "importance": "somewhat"},
      {"articleURL": "https://www.latimes.com/politics/la-me-pol-knight-brayton-facebook-20181031-story.html", "title": "Veteran featured in GOP congressman\u2019s midterm election ad posted racist rants", "description": "Rep. Steve Knight of Palmdale has posted a television ad showing a veteran praising the Republican congressman for helping him get a lung transplant. It turns out that veteran has posted dozens of racist, anti-Semitic and anti-Muslim comments on Facebook.", "imageURL": "https://i.imgur.com/zMMvCYb.jpg", "genre": "Investigative", "publication": "LA Times", "importance": "strongly"},
      {"articleURL": "https://www.wsj.com/articles/floridas-red-tide-stings-tourist-industry-1534334400", "title": "Florida\u2019s red tide stings tourist industry", "description": "Local tourist boards are concerned the impact could be felt for a while, as news of the red tide spreads and more tourists cancel or adjust their trips.", "imageURL": "https://i.imgur.com/2dMVsfM.jpg", "genre": "Investigative", "publication": "Wall Street Journal", "importance": "strongly"},
      {"articleURL": "https://www.wsj.com/articles/move-the-furniture-its-time-for-a-drone-race-1532955600", "title": "Move the furniture, it\u2019s time for a drone race", "description": "El Original doesn\u2019t always close down for the night after the last round of margaritas. Occasionally, the Tex-Mex restaurant in Hell\u2019s Kitchen keeps humming \u2014 as a late-night venue for drone races.", "imageURL": "https://i.imgur.com/8m8NMWR.jpg", "genre": "Features", "publication": "Wall Street Journal", "importance": "strongly"},
      {"articleURL": "https://www.seattletimes.com/seattle-news/seattles-pesticide-phaseout-lags-potentially-harmful-products-used-in-parks/", "title": "Seattle\u2019s pesticide phaseout lags: Potentially harmful products used in parks", "description": "Despite the city\u2019s commitment to lower its use of pesticides, Seattle continues to apply thousands of gallons of pesticides to its parks and golf courses each year. And some parks the city branded \u201cpesticide-free\u201d have been treated with pesticides as recently as this spring.", "imageURL": "https://i.imgur.com/yiph5G0.jpg", "genre": "Investigative", "publication": "Seattle Times", "importance": "strongly"},
      {"articleURL": "http://features.yaledailynews.com/blog/2017/10/13/yale-targeted-in-federal-title-ix-investigation/", "title": "Yale targeted in federal Title IX investigation", "description": "Doe still has a federal lawsuit awaiting resolution in Hartford, alongside two others filed by male Yale students \u2014 three lawsuits that allege Yale has tipped the scales against the accused in sexual misconduct proceedings.", "imageURL": "https://i.imgur.com/3wtNfIT.jpg", "genre": "Investigative", "publication": "YDN", "importance": "strongly"},
    ],
  },
  plugins: [
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images/`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `data`,
        path: `${__dirname}/src/data/`,
      },
    },
    'gatsby-transformer-sharp',
    'gatsby-transformer-json',
    'gatsby-plugin-sharp',
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: 'gatsby-starter-default',
        short_name: 'starter',
        start_url: '/',
        background_color: '#663399',
        theme_color: '#663399',
        display: 'minimal-ui',
        icon: 'src/images/favicon.png',
      },
    }
  ],
}
